import Head from "next/head";
import React from "react";
import HomeCompIndex from "../components/home/ui";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Navbar /> */}
        <HomeCompIndex />
      </main>
    </div>
  );
}
